import fs from 'fs';
import path from 'path';

function loadEnv() {
  const envPath = path.resolve('.env');
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf8').split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const idx = trimmed.indexOf('=');
        if (idx !== -1) {
          const key = trimmed.slice(0, idx).trim();
          const val = trimmed.slice(idx + 1).trim();
          if (!process.env[key]) {
            process.env[key] = val;
          }
        }
      }
    }
  }
}

loadEnv();

const testbedPluginDir = process.env.OBSIDIAN_VAULT_DIR;

console.log('=== Folder Notes TestBed Diagnostic Harness ===');
console.log(`Target Plugin Directory: ${testbedPluginDir}`);

if (!testbedPluginDir || !fs.existsSync(testbedPluginDir)) {
  console.error(`Error: Plugin directory does not exist at ${testbedPluginDir}`);
  process.exit(1);
}

const requiredFiles = ['main.js', 'manifest.json', 'styles.css'];
let allPresent = true;

for (const file of requiredFiles) {
  const filePath = path.join(testbedPluginDir, file);
  if (fs.existsSync(filePath)) {
    const stat = fs.statSync(filePath);
    console.log(`[PASS] ${file} exists (${stat.size} bytes, modified: ${stat.mtime.toISOString()})`);
  } else {
    console.error(`[FAIL] ${file} is MISSING from ${testbedPluginDir}`);
    allPresent = false;
  }
}

// Check data.json
const dataJsonPath = path.join(testbedPluginDir, 'data.json');
if (fs.existsSync(dataJsonPath)) {
  try {
    const data = JSON.parse(fs.readFileSync(dataJsonPath, 'utf8'));
    console.log(`[PASS] data.json valid. Template: "${data.folderNoteName}", Storage: "${data.storageLocation}", SyncFolderName: ${data.syncFolderName}`);
  } catch (err) {
    console.warn(`[WARN] data.json could not be parsed:`, err.message);
  }
} else {
  console.log('[INFO] data.json not found in testbed plugin dir (will be generated by Obsidian on load).');
}

// Check debug.log
const logPath = path.join(testbedPluginDir, 'debug.log');
if (fs.existsSync(logPath)) {
  const logStat = fs.statSync(logPath);
  console.log(`[PASS] debug.log exists (${logStat.size} bytes, last modified: ${logStat.mtime.toISOString()})`);
  const logContent = fs.readFileSync(logPath, 'utf8');
  const lines = logContent.split('\n').filter(l => l.trim().length > 0);
  console.log(`[INFO] Total log entries in debug.log: ${lines.length}`);
  console.log('--- Last 5 log entries ---');
  lines.slice(-5).forEach(line => console.log(`  ${line}`));
} else {
  console.log('[INFO] debug.log not yet created (will be created when Obsidian is launched with the plugin).');
}

if (allPresent) {
  console.log('\n[SUCCESS] TestBed plugin directory is healthy, fully deployed, and ready for live verification!');
} else {
  console.error('\n[FAILED] TestBed verification failed.');
  process.exit(1);
}
